### ISSUE TITLE
Create a proposal for menu in main page

### ISSUE THREAD

**Issue by neossoftware** [neossoftware/neossystem#10]
Create a proposal for menu in main page

**Comment by neossoftware** [comment]
@hhugohm  Could you please create a proposal for main menu, If it is hard for you please let me know

**Comment by neossoftware** [comment]
@hhugohm Hugo ya lo pense mejor esta tarea yo la tomo va.

**Comment by hhugohm** [comment]
Ok, sin problemas toma la task
