### ISSUE TITLE
Create a layout for every course.

### ISSUE THREAD

**Issue by neossoftware** [neossoftware/neossystem#13]
Create a layout for every course

**Comment by neossoftware** [comment]
Add a layout for every course, We can use tabs to have the following information

General Description, Training Structure ,  Specify the cost of each course.

For example this is the first draft.

![image](https://cloud.githubusercontent.com/assets/561434/22450539/f84fff0c-e72c-11e6-9e69-fdd22e5d3785.png)

**Comment by hhugohm** [comment]
I think that this issue must be closed because I remember that you completed this task, do you agree with me?
