### ISSUE TITLE
Crear temario de Git

### ISSUE THREAD

**Issue by neossoftware** [neossoftware/neossystem#7]
En esta parte el sistema tiene que tener la pagina con el temario del curso

**Comment by neossoftware** [comment]
I am going to take this task

**Comment by neossoftware** [comment]
@hhugohm  Tu apoyo para crear el temario del curso de Git   GitHub, puedes darte una idea del libro https://git-scm.com/book/es/v2 este libro esta en español, como habiamos visto un curso para 10 hrs tambien no queremos un curso para super expertos.

**Comment by hhugohm** [comment]
Ok, comienzo con el temario del curso.
Saludos

**Comment by hhugohm** [comment]
Done with PR https://github.com/neossoftware/neossystem/pull/14
